name: CI Build

# Perform CI builds for pull requests targeting the dev branches.

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - gh-actions-test

jobs:
  linux-build:
    name: Ubuntu GCC Release
    runs-on: [self-hosted, linux, build]
    strategy:
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run build script
        run: python3 scripts/build.py --config release --skip-check-code-style --parallel 4 --test-apps
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts
          path: build/linux/x64/output

  linux-test:
    name: Run linux tests
    needs: linux-build
    runs-on: [self-hosted, linux, test]
    steps:
      - name: Run test app test cases
        id: test_apps
        run: |
          cd build/linux/x64/output/test
          ./run-tests.sh
